//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="IRemoteService")]
public interface IRemoteService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IRemoteService/Ping", ReplyAction="http://Microsoft.ServiceModel.Samples/IRemoteService/AddResponse")]
    string Ping();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IRemoteService/Echo", ReplyAction="http://Microsoft.ServiceModel.Samples/IRemoteService/SubtractResponse")]
    string Echo(string text);

    [System.ServiceModel.OperationContractAttribute(Action = "http://Microsoft.ServiceModel.Samples/IRemoteService/Login", ReplyAction = "http://Microsoft.ServiceModel.Samples/IRemoteService/SubtractResponse")]
    bool Login(string name, string pass);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRemoteServiceChannel : IRemoteService, System.ServiceModel.IClientChannel
{
}

public partial class RemoteClient : IRemoteService
{
    
    public RemoteClient()
    {
    }
    

    public string Ping()
    {
        return "localhost";
        //return base.Channel.Ping();
    }

    public string Echo(string text)
    {
        return $"Server echo with text: { text }";
        //return base.Channel.Echo(text);
    }

    public bool Login(string name, string pass)
    {
        return name == "Rostyk" && pass == "111";
        //return base.Channel.Login(name, pass);
    }
}
